version: '3.8'

services:
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data

  todo:
    build: .
    command:
      - ./main
    ports:
      - "8080:8080"
    depends_on:
      - db
